name: PR-preview

# Trigger the workflow on pull request activity
on:
  pull_request:
    branches:
      - main

jobs:
  preview-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r biometrics/requirements.txt

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build biometrics/biometrics

      # Upload the book's HTML as an artifact
      - name: Upload website
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: biometrics/biometrics/_build/html
